### PR TITLE
Fix duplication of UI fields in move_product handler.

### PR DESCRIPTION
**Pull request by neekfenwick**
Code was missing the trick used in 'copy_product' to only output rows from $content that had not already been output.

### CODE REVIEW

**Comment by neekfenwick** [comment]
Fixes #11

**Comment by neekfenwick** [comment]
Please note I've pushed a second commit, so you would want to Squash Merge this PR at this point (using the green dropdown button that by default reads "Rebase and merge").

**Comment by torvista** [comment]
Looks fine to me.
I assume Squash Merge would be the correct action (which **was** disabled)?

**Comment by neekfenwick** [comment]
> Looks fine to me. I assume Squash Merge would be the correct action (which **was** disabled)?

Weird that it was disabled.  I squash merged this yesterday, the first time I've done this through the github UI, as I've never had commit privs to a github repo that wasn't my own before :P I see this approach has cleared up some other issues too, nice :)

**Comment by CeonSupport** [comment]
Too bad between the two of you that this is considered the solution to use. So where in the instruction do we now incorporate that we have taken over any edits made in the base file's $content variables?

Why does this issue appear in 1.5.8, but was not reported in 1.5.7?

This was the path we were going to take in eliminating file edits; however; wiping that variable out instead of adding to it only makes things harder to troubleshoot if not impossible.

**Pull request merged**
